name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover


  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/ci-cd-app:latest .

      - name: Push Docker Image to DockerHub
        run: docker push your-dockerhub-username/ci-cd-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/ci-cd-app:latest
            docker stop my_app || true
            docker rm my_app || true
            docker run -d -p 80:5000 --name my_app your-dockerhub-username/ci-cd-app:latest
